editPin -pin clk -layer 2 -fixedPin -assign {20.86 0} -side TOP
editPin -pin reset -layer 2 -fixedPin -assign {21.42 0} -side TOP
editPin -pin data_in -layer 2 -fixedPin -assign {21.98 0} -side TOP
editPin -pin clk15k_in -layer 2 -fixedPin -assign {22.54 0} -side TOP
editPin -pin data_switch -layer 2 -fixedPin -assign {29.82 0} -side TOP
editPin -pin clk15k_switch -layer 2 -fixedPin -assign {30.38 0} -side TOP
editPin -pin R -layer 2 -fixedPin -assign {30.94 0} -side TOP
editPin -pin G -layer 2 -fixedPin -assign {31.50 0} -side TOP
editPin -pin B -layer 2 -fixedPin -assign {32.06 0} -side TOP
editPin -pin V -layer 2 -fixedPin -assign {32.62 0} -side TOP
editPin -pin H -layer 2 -fixedPin -assign {33.18 0} -side TOP
