read_hdl -vhdl {color.vhd}
read_hdl -vhdl {counter25mhz.vhd}
read_hdl -vhdl {edge_debounce.vhd}
read_hdl -vhdl {flipflop.vhd}
read_hdl -vhdl {logic_top.vhd}
read_hdl -vhdl {main_fsm.vhd}
read_hdl -vhdl {mouse.vhd}
read_hdl -vhdl {mux.vhd}
read_hdl -vhdl {sendFSM.vhd}
read_hdl -vhdl {shfitregister_11bit.vhd}
read_hdl -vhdl {shiftregister_9bit.vhd}
read_hdl -vhdl {timebase.vhd}
read_hdl -vhdl {top.vhd}
read_hdl -vhdl {x.vhd}
read_hdl -vhdl {y.vhd}
read_hdl -vhdl {color-behaviour_color.vhd}
read_hdl -vhdl {counter25mhz-behav.vhd}
read_hdl -vhdl {edge_debounce-behav.vhd}
read_hdl -vhdl {flipflop-behav.vhd}
read_hdl -vhdl {logic_top-behaviour_logic_top.vhd}
read_hdl -vhdl {main_fsm-behav.vhd}
read_hdl -vhdl {mouse-behav.vhd}
read_hdl -vhdl {mux-behav.vhd}
read_hdl -vhdl {sendFSM-behav.vhd}
read_hdl -vhdl {shiftregister_11bit-behav.vhd}
read_hdl -vhdl {shiftregister_9bit-behav.vhd}
read_hdl -vhdl {timebase-behav.vhd}
read_hdl -vhdl {top-behav.vhd}
read_hdl -vhdl {x-behaviour_x.vhd}
read_hdl -vhdl {y-behaviour_y.vhd}
read_hdl -vhdl {color_behaviour_color_cfg.vhd}
read_hdl -vhdl {y_behaviour_y_cfg.vhd}
read_hdl -vhdl {x_behaviour_x_cfg.vhd}
read_hdl -vhdl {shiftregister_11bit_behav_cfg.vhd}
read_hdl -vhdl {flipflop_behav_cfg.vhd}
read_hdl -vhdl {main_fsm_behav_cfg.vhd}
read_hdl -vhdl {timebase_behav_cfg.vhd}
read_hdl -vhdl {mux_behav_cfg.vhd}
read_hdl -vhdl {sendfsm_behav_cfg.vhd}
read_hdl -vhdl {shiftregister_9bit_behav_cfg.vhd}
read_hdl -vhdl {edge_debounce_behav_cfg.vhd}
read_hdl -vhdl {counter25mhz_behav_cfg.vhd}
read_hdl -vhdl {logic_top_behaviour_logic_top_cfg.vhd}
read_hdl -vhdl {mouse_behav_cfg.vhd}
read_hdl -vhdl {top_behav_cfg.vhd}
