read_hdl -vhdl {counter25mhz.vhd}
read_hdl -vhdl {edge_detector.vhd}
read_hdl -vhdl {flipflop.vhd}
read_hdl -vhdl {main_fsm.vhd}
read_hdl -vhdl {mouse.vhd}
read_hdl -vhdl {mux.vhd}
read_hdl -vhdl {sendFSM.vhd}
read_hdl -vhdl {shfitregister_11bit.vhd}
read_hdl -vhdl {shiftregister_9bit.vhd}
read_hdl -vhdl {timebase.vhd}
read_hdl -vhdl {counter25mhz-behav.vhd}
read_hdl -vhdl {edge_detector-behav.vhd}
read_hdl -vhdl {flipflop-behav.vhd}
read_hdl -vhdl {main_fsm-behav.vhd}
read_hdl -vhdl {mouse-behav.vhd}
read_hdl -vhdl {mux-behav.vhd}
read_hdl -vhdl {sendFSM-behav.vhd}
read_hdl -vhdl {shiftregister_11bit-behav.vhd}
read_hdl -vhdl {shiftregister_9bit-behav.vhd}
read_hdl -vhdl {timebase-behav.vhd}
read_hdl -vhdl {shiftregister_11bit_behav_cfg.vhd}
read_hdl -vhdl {flipflop_behav_cfg.vhd}
read_hdl -vhdl {main_fsm_behav_cfg.vhd}
read_hdl -vhdl {timebase_behav_cfg.vhd}
read_hdl -vhdl {mux_behav_cfg.vhd}
read_hdl -vhdl {sendfsm_behav_cfg.vhd}
read_hdl -vhdl {shiftregister_9bit_behav_cfg.vhd}
read_hdl -vhdl {edge_detector_behav_cfg.vhd}
read_hdl -vhdl {counter25mhz_behav_cfg.vhd}
read_hdl -vhdl {mouse_behav_cfg.vhd}
