editPin -pin Data_in -layer 2 -fixedPin -assign {20.86 0} -side TOP
editPin -pin Clk15k -layer 2 -fixedPin -assign {21.42 0} -side TOP
editPin -pin clk -layer 2 -fixedPin -assign {21.98 0} -side TOP
editPin -pin reset -layer 2 -fixedPin -assign {22.54 0} -side TOP
editPin -pin countlow -layer 2 -fixedPin -assign {23.10 0} -side TOP
editPin -pin DataSwitch -layer 2 -fixedPin -assign {29.82 0} -side TOP
editPin -pin ClkSwitch -layer 2 -fixedPin -assign {30.38 0} -side TOP
editPin -pin rescount -layer 2 -fixedPin -assign {30.94 0} -side TOP
editPin -pin draw -layer 2 -fixedPin -assign {31.50 0} -side TOP
editPin -pin {output_color[2]} -layer 2 -fixedPin -assign {32.06 0} -side TOP
editPin -pin {output_color[1]} -layer 2 -fixedPin -assign {32.62 0} -side TOP
editPin -pin {output_color[0]} -layer 2 -fixedPin -assign {33.18 0} -side TOP
editPin -pin {tempx[3]} -layer 2 -fixedPin -assign {33.74 0} -side TOP
editPin -pin {tempx[2]} -layer 2 -fixedPin -assign {34.30 0} -side TOP
editPin -pin {tempx[1]} -layer 2 -fixedPin -assign {34.86 0} -side TOP
editPin -pin {tempx[0]} -layer 2 -fixedPin -assign {35.42 0} -side TOP
editPin -pin {tempy[3]} -layer 2 -fixedPin -assign {35.98 0} -side TOP
editPin -pin {tempy[2]} -layer 2 -fixedPin -assign {36.54 0} -side TOP
editPin -pin {tempy[1]} -layer 2 -fixedPin -assign {37.10 0} -side TOP
editPin -pin {tempy[0]} -layer 2 -fixedPin -assign {37.66 0} -side TOP
