editPin -pin Handshake_in -layer 2 -fixedPin -assign {20.86 0} -side TOP
editPin -pin Data_in -layer 2 -fixedPin -assign {21.42 0} -side TOP
editPin -pin Clk15k -layer 2 -fixedPin -assign {21.98 0} -side TOP
editPin -pin clk -layer 2 -fixedPin -assign {22.54 0} -side TOP
editPin -pin reset -layer 2 -fixedPin -assign {23.10 0} -side TOP
editPin -pin {mouseX[2]} -layer 2 -fixedPin -assign {29.82 0} -side TOP
editPin -pin {mouseX[1]} -layer 2 -fixedPin -assign {30.38 0} -side TOP
editPin -pin {mouseX[0]} -layer 2 -fixedPin -assign {30.94 0} -side TOP
editPin -pin {mouseY[2]} -layer 2 -fixedPin -assign {31.50 0} -side TOP
editPin -pin {mouseY[1]} -layer 2 -fixedPin -assign {32.06 0} -side TOP
editPin -pin {mouseY[0]} -layer 2 -fixedPin -assign {32.62 0} -side TOP
editPin -pin {buttons[4]} -layer 2 -fixedPin -assign {33.18 0} -side TOP
editPin -pin {buttons[3]} -layer 2 -fixedPin -assign {33.74 0} -side TOP
editPin -pin {buttons[2]} -layer 2 -fixedPin -assign {34.30 0} -side TOP
editPin -pin {buttons[1]} -layer 2 -fixedPin -assign {34.86 0} -side TOP
editPin -pin {buttons[0]} -layer 2 -fixedPin -assign {35.42 0} -side TOP
editPin -pin Handshake_out -layer 2 -fixedPin -assign {35.98 0} -side TOP
editPin -pin DataSwitch -layer 2 -fixedPin -assign {36.54 0} -side TOP
editPin -pin ClkSwitch -layer 2 -fixedPin -assign {37.10 0} -side TOP
